#!/usr/bin/env python3
"""
build_sandbox.py - Build container images for sandboxed CLI execution.

Purpose:
    Builds Docker or Podman container images containing the Joshu CLI
    for isolated execution environments.

Inputs:
    --engine          Container engine to use (docker|podman|auto)
    --tag             Image tag (default: latest)
    --verbose         Enable verbose output

Outputs:
    - Container image tagged as joshu-sandbox:<tag>

Side Effects:
    - Creates container image in local registry
    - May download base images

Safety Considerations:
    - Requires container runtime to be installed
    - Uses buildx/build for image creation
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPTS_DIR.parent


def log(message: str, verbose: bool = True) -> None:
    """Print a log message if verbose mode is enabled."""
    if verbose:
        print(f"[build_sandbox] {message}")


def log_error(message: str) -> None:
    """Print an error message."""
    print(f"[build_sandbox] ERROR: {message}", file=sys.stderr)


def log_success(message: str) -> None:
    """Print a success message."""
    print(f"[build_sandbox] ✓ {message}")


def detect_container_engine() -> str | None:
    """Detect available container engine (Docker or Podman)."""
    for engine in ["docker", "podman"]:
        if shutil.which(engine):
            return engine
    return None


def check_engine_running(engine: str) -> bool:
    """Check if the container engine is running."""
    try:
        result = subprocess.run(
            [engine, "info"],
            capture_output=True,
            text=True,
            timeout=10,
        )
        return result.returncode == 0
    except Exception:
        return False


def create_dockerfile(work_dir: Path) -> Path:
    """Create a Dockerfile for the sandbox image."""
    dockerfile = work_dir / "Dockerfile.sandbox"

    content = """# Joshu CLI Sandbox Image
# Auto-generated by build_sandbox.py

FROM python:3.13-slim

LABEL maintainer="Joshu Community"
LABEL description="Sandboxed environment for Joshu CLI"

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \\
    git \\
    && rm -rf /var/lib/apt/lists/*

# Create non-root user
RUN useradd -m -s /bin/bash joshu

# Set working directory
WORKDIR /app

# Copy project files
COPY --chown=joshu:joshu . /app/

# Install Joshu CLI
RUN pip install --no-cache-dir -e .

# Switch to non-root user
USER joshu

# Set entrypoint
ENTRYPOINT ["joshu"]
CMD ["--help"]
"""

    dockerfile.write_text(content)
    return dockerfile


def build_image(
    engine: str,
    tag: str,
    verbose: bool = False,
) -> bool:
    """Build the container image."""
    dockerfile = create_dockerfile(PROJECT_ROOT)

    image_name = f"joshu-sandbox:{tag}"

    cmd = [
        engine,
        "build",
        "-f",
        str(dockerfile),
        "-t",
        image_name,
        str(PROJECT_ROOT),
    ]

    log(f"Building image: {image_name}", verbose)
    log(f"Command: {' '.join(cmd)}", verbose)

    try:
        result = subprocess.run(
            cmd,
            cwd=PROJECT_ROOT,
            capture_output=not verbose,
            text=True,
        )

        if result.returncode != 0:
            log_error("Image build failed")
            if not verbose and result.stderr:
                print(result.stderr)
            return False

        log_success(f"Built image: {image_name}")
        return True

    except Exception as e:
        log_error(f"Build failed: {e}")
        return False
    finally:
        # Cleanup Dockerfile
        if dockerfile.exists():
            dockerfile.unlink()


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Build container images for sandboxed CLI execution",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/build_sandbox.py
    python scripts/build_sandbox.py --engine docker --tag v0.1.0
        """,
    )
    parser.add_argument(
        "--engine",
        choices=["docker", "podman", "auto"],
        default="auto",
        help="Container engine to use (default: auto-detect)",
    )
    parser.add_argument(
        "--tag",
        default="latest",
        help="Image tag (default: latest)",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose output",
    )

    args = parser.parse_args()

    # Detect or use specified engine
    if args.engine == "auto":
        engine = detect_container_engine()
        if not engine:
            log_error("No container engine found (Docker or Podman)")
            log_error("Please install Docker or Podman to build sandbox images")
            return 1
    else:
        engine = args.engine
        if not shutil.which(engine):
            log_error(f"{engine} is not installed")
            return 1

    log(f"Using container engine: {engine}", args.verbose)

    # Check engine is running
    if not check_engine_running(engine):
        log_error(f"{engine} is not running")
        log_error(f"Please start {engine} and try again")
        return 1

    log_success(f"{engine} is available and running")

    # Build the image
    if not build_image(engine, args.tag, args.verbose):
        return 1

    print("\nTo run the sandbox:")
    print(f"  {engine} run -it --rm joshu-sandbox:{args.tag}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
