#!/usr/bin/env python3
"""
generate_git_info.py - Embed Git commit hash and version into Python source.

Purpose:
    Generates a _version.py file containing version information,
    Git commit hash, and build timestamp for runtime introspection.

Inputs:
    --output PATH     Output file path (default: src/joshu/_version.py)
    --verbose         Enable verbose output

Outputs:
    - Generated _version.py file with version metadata

Side Effects:
    - Overwrites existing _version.py

Safety Considerations:
    - Idempotent: same inputs produce same outputs
    - Can be safely run multiple times
"""

import argparse
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import tomllib
except ImportError:
    import tomli as tomllib  # type: ignore

SCRIPTS_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPTS_DIR.parent


def log(message: str, verbose: bool = True) -> None:
    """Print a log message if verbose mode is enabled."""
    if verbose:
        print(f"[generate_git_info] {message}")


def log_error(message: str) -> None:
    """Print an error message."""
    print(f"[generate_git_info] ERROR: {message}", file=sys.stderr)


def log_success(message: str) -> None:
    """Print a success message."""
    print(f"[generate_git_info] ✓ {message}")


def get_version_from_pyproject() -> str:
    """Read version from pyproject.toml."""
    pyproject_path = PROJECT_ROOT / "pyproject.toml"

    if not pyproject_path.exists():
        log_error("pyproject.toml not found")
        return "0.0.0"

    try:
        with open(pyproject_path, "rb") as f:
            data = tomllib.load(f)
        return data.get("project", {}).get("version", "0.0.0")
    except Exception as e:
        log_error(f"Failed to read pyproject.toml: {e}")
        return "0.0.0"


def get_git_commit() -> str:
    """Get current Git commit hash."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def get_git_branch() -> str:
    """Get current Git branch name."""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--abbrev-ref", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return result.stdout.strip()
    except Exception:
        pass
    return "unknown"


def get_git_dirty() -> bool:
    """Check if working directory has uncommitted changes."""
    try:
        result = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            return len(result.stdout.strip()) > 0
    except Exception:
        pass
    return False


def generate_version_file(output_path: Path, verbose: bool = False) -> bool:
    """Generate _version.py with version metadata."""
    version = get_version_from_pyproject()
    commit = get_git_commit()
    branch = get_git_branch()
    dirty = get_git_dirty()
    build_time = datetime.now(timezone.utc).isoformat()

    log(f"Version: {version}", verbose)
    log(f"Commit: {commit[:8]}...", verbose)
    log(f"Branch: {branch}", verbose)
    log(f"Dirty: {dirty}", verbose)

    content = f'''"""
Auto-generated version information.

DO NOT EDIT MANUALLY - Generated by scripts/generate_git_info.py
"""

__version__ = "{version}"
__git_commit__ = "{commit}"
__git_branch__ = "{branch}"
__git_dirty__ = {dirty}
__build_time__ = "{build_time}"


def get_version_string() -> str:
    """Get formatted version string for display."""
    version_str = f"{{__version__}}"
    if __git_dirty__:
        version_str += "-dirty"
    version_str += f" ({{__git_commit__[:8]}})"
    return version_str
'''

    # Ensure parent directory exists
    output_path.parent.mkdir(parents=True, exist_ok=True)

    try:
        output_path.write_text(content)
        log_success(f"Generated {output_path}")
        return True
    except Exception as e:
        log_error(f"Failed to write {output_path}: {e}")
        return False


def main() -> int:
    """Main entry point."""
    parser = argparse.ArgumentParser(
        description="Generate _version.py with Git and version info",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python scripts/generate_git_info.py
    python scripts/generate_git_info.py --output src/joshu/_version.py
        """,
    )
    parser.add_argument(
        "--output",
        "-o",
        type=Path,
        default=PROJECT_ROOT / "src" / "joshu" / "_version.py",
        help="Output file path (default: src/joshu/_version.py)",
    )
    parser.add_argument(
        "--verbose",
        "-v",
        action="store_true",
        help="Enable verbose output",
    )

    args = parser.parse_args()

    output = args.output if args.output.is_absolute() else PROJECT_ROOT / args.output

    if not generate_version_file(output, args.verbose):
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
